INSERT INTO `department` (`department_short`, `department_long`) VALUES  
('AAH', 'Art and Architectural Hist'),
('ACCT', 'Accounting'),
('AGED', 'Agricultural Education'),
('AGM', 'Agricultural Mechanization'),
('AGRB', 'Agribusiness'),
('AL', 'Athletic Leadership'),
('ANTH', 'Anthropology'),
('APEC', 'Applied Economics'),
('ARCH', 'Architecture'),
('ART', 'Art'),
('AS', 'Aerospace Studies'),
('ASL', 'American Sign Language'),
('ASTR', 'Astronomy'),
('AUD', 'Audio Technology'),
('AUE', 'Automotive Engineering'),
('AVS', 'Animal and Vet Sciences'),
('BCHM', 'Biochemistry'),
('BE', 'Biosystems Engineering'),
('BIOE', 'Bioengineering'),
('BIOL', 'Biology'),
('BMOL', 'Biomolecular Engineering'),
('BUS', 'Business'),
('CE', 'Civil Engineering'),
('CES', 'Coll of Eng and Science'),
('CH', 'Chemistry'),
('CHE', 'Chemical Engineering'),
('CHIN', 'Chinese'),
('COMM', 'Communication'),
('COOP', 'Cooperative Education'),
('CPSC', 'Computer Science'),
('CRP', 'City and Regional Planning'),
('CSM', 'Construction Sci and Mgt'),
('CU', 'Clemson University'),
('CVT', 'Cardiovascular Technology'),
('DANC', 'Dance'),
('DPA', 'Digital Production Arts'),
('ECE', 'Electrical and Comp Engr'),
('ECON', 'Economics'),
('ED', 'Education'),
('EDC', 'Educational Counseling'),
('EDEC', 'Early Childhood Education'),
('EDEL', 'Elementary Education'),
('EDF', 'Educational Foundations'),
('EDHD', 'Education and Human Devel'),
('EDL', 'Educational Leadership'),
('EDLT', 'Literacy'),
('EDML', 'Middle-Level Education'),
('EDSA', 'Education Student Affairs'),
('EDSC', 'Secondary Education'),
('EDSP', 'Special Education'),
('EES', 'Env Engr and Science'),
('ELE', 'Exec Lead and Entrepren'),
('ENGL', 'English'),
('ENGR', 'Engineering'),
('ENR', 'Environmental and Nat Res'),
('ENSP', 'Environ Sci and Policy'),
('ENT', 'Entomology'),
('ENTR', 'Entrepreneurship'),
('ESED', 'Eng & Science Educ'),
('ETOX', 'Environmental Toxicology'),
('FCS', 'Family and Comm Studies'),
('FDSC', 'Food Science'),
('FDTH', 'Food Technology'),
('FIN', 'Finance'),
('FNR', 'Forestry and Nat Resources'),
('FOR', 'Forestry'),
('FR', 'French'),
('GC', 'Graphic Communications'),
('GEN', 'Genetics'),
('GEOG', 'Geography'),
('GEOL', 'Geology'),
('GER', 'German'),
('GRAD', 'Graduate Studies'),
('GW', 'Great Works'),
('HCC', 'Human-Centered Computing'),
('HCG', 'Health Care Genetics'),
('HEHD', 'Health, Ed and Human Dev'),
('HIST', 'History'),
('HLTH', 'Health'),
('HON', 'Honors'),
('HORT', 'Horticulture'),
('HP', 'Historic Preservation'),
('HRD', 'Human Resource Development'),
('HSPV', 'Historic Preserv (CofC)'),
('HUM', 'Humanities'),
('IE', 'Industrial Engineering'),
('INNO', 'Innovation'),
('INT', 'Career Ctr Internship Prog'),
('IS', 'International Studies'),
('ITAL', 'Italian'),
('JAPN', 'Japanese'),
('JUST', 'Justice Studies'),
('LANG', 'Language'),
('LARC', 'Landscape Architecture'),
('LAW', 'Law'),
('LIB', 'Library'),
('LIH', 'Language and Int Health'),
('LIT', 'Language and Int Trade'),
('LS', 'Leisure Skills'),
('MATH', 'Mathematical Sciences'),
('MBA', 'Business Administration'),
('ME', 'Mechanical Engineering'),
('MGT', 'Management'),
('MICR', 'Microbiology'),
('MKT', 'Marketing'),
('ML', 'Military Leadership'),
('MSE', 'Materials Sci and Eng'),
('MUSC', 'Music'),
('NPL', 'Nonprofit Leadership'),
('NURS', 'Nursing'),
('NUTR', 'Nutrition'),
('PA', 'Performing Arts'),
('PADM', 'Public Administration'),
('PAS', 'Pan African Studies'),
('PDBE', 'Plan Design and Built Env'),
('PES', 'Plant and Env Sci'),
('PHIL', 'Philosophy'),
('PHSC', 'Physical Science'),
('PHYS', 'Physics'),
('PKSC', 'Packaging Science'),
('PLPA', 'Plant Pathology'),
('POSC', 'Political Science'),
('POST', 'Policy Studies'),
('PRTM', 'Parks Rec and Tourism Mgt'),
('PSYC', 'Psychology'),
('RCID', 'Rhet Comm and Info Design'),
('RED', 'Real Estate Development'),
('REL', 'Religion'),
('RS', 'Rural Sociology'),
('RUSS', 'Russian'),
('SAP', 'Study Abroad Program'),
('SOC', 'Sociology'),
('SPAN', 'Spanish'),
('STAT', 'Statistics'),
('STS', 'Sci and Tech in Society'),
('THEA', 'Theatre'),
('TSAP', 'Transfer Study Abroad Prg'),
('WCIN', 'World Cinema'),
('WFB', 'Wildlife and Fish Biology'),
('WS', 'Women\'s Studies'),
('YDP', 'Youth Development Programs');